[package]
name = "sebas/manic-mines"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.7"
Component = "sleitnick/component@2.4.8"
maid = "alexinite/maid@2.3.2"
Roact = "roblox/roact@1.4.4"
Flipper = "reselim/flipper@2.0.0"
TestEZ = "roblox/testez@0.4.1"
cmdr = "evaera/cmdr@1.12.0"
Promise = "evaera/promise@4.0.0"
octo-tree = "sleitnick/octo-tree@0.3.1"
Iris = "sirmallard/iris@2.4.0"
ImGizmo = "jakeywastaken/imgizmo@^3.5.0"
NeoHotbar = "imavafe/neohotbar@1.1.1"