name: Create Nightly Release

on:
  push:
    branches:
      - 'Dev'
      
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'Dev'

      - name: Get latest commit message
        id: get_commit_message
        run: echo "message=$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ env.message }}
          tag: Nightly
          prerelease: true
