name: Create Nightly Release

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest commit message
        id: get_commit_message
        run: echo "message=$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: "Nightly"
          release_name: ${{ env.message }}
          body: "Nightly release created from commit ${{ github.sha }}."
          draft: false
          prerelease: true  # Mark as prerelease
